:ok_hand:

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,8 +27,29 @@ jobs:
           paths: 
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
+  back-deploy-heroku:
+    docker:
+      - image: buildpack-deps:trusty
+    steps:
+       - checkout
+       - run:
+           name: Heroku Deploy
+           command: |
+             git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
+       - run:
+           name: Smoke Test
+           command: |
+             # Heroku deploy command will pass even if application crashes. Simple smoke test to make sure app is up.
+             HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://$HEROKU_APP_NAME.herokuapp.com/`
+             if [ "$HTTPCODE" -ne 200 ];then
+                 echo "heroku app not responding, failing deploy"
+                 exit 1
+             fi
 workflows:
   version: 2
   build-and-test:
     jobs:
       - install
+      - back-deploy-heroku:
+          requires:
+            - install
